version: '3.8'
services:
  app:
    container_name: myfirst_dockerized_rest_server
    build:
      dockerfile: rest_api/Dockerfile
      context: .
    ports:
      - 8000:80
    depends_on:
      - db
    volumes:  
      - ./rest_api:/var/www/html

  db:
    container_name: myfirst_dockerized_database_server
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./db_dumps/world.sql:/docker-entrypoint-initdb.d/world.sql